apiVersion: v2
name: seed-node
description: A Helm chart for Mina Protocol's seed nodes
type: application
version: 0.6.0
appVersion: 1.16.0
annotations:
  artifacthub.io/changes: |
    - add seed-node static external IP chart value
    - enable multiple seed-node deployment configurations
    - add peers list URL chart value
dependencies:
  - name: common-utilities
    version: 0.0.8
    repository: "https://coda-charts.storage.googleapis.com"
icon: https://storage.googleapis.com/coda-charts/Mina_Icon_Secondary_RGB_Black.png
keywords:
- seed
- mina
- testnet
home: https://minaprotocol.com/
sources:
- https://github.com/MinaProtocol/mina/tree/develop/helm/seed-node
