apiVersion: v2
name: block-producer
description: A Helm chart for Mina Protocol's block producing network nodes
type: application
<<<<<<< HEAD
version: 0.5.1
appVersion: 1.16.0
annotations:
  artifacthub.io/changes: |
    - add toggle for archiving daemon activity
=======
version: 0.5.2
appVersion: 1.16.0
annotations:
  artifacthub.io/changes: |
    - fix peer-list-url flag
>>>>>>> origin/multi_archive_deploys
dependencies:
  - name: common-utilities
    version: 0.0.8
    repository: "https://coda-charts.storage.googleapis.com"
icon: https://storage.googleapis.com/coda-charts/Mina_Icon_Secondary_RGB_Black.png
keywords:
- block-producer
- stake
- delegate
- mina
- testnet
home: https://minaprotocol.com/
sources:
- https://github.com/MinaProtocol/mina/tree/develop/helm/block-producer

